# fly.toml file generated for fiufit-gateway on 2023-04-03T16:31:33-03:00

app = "fiufit-gateway"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gru"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[env]
HOST = "0.0.0.0"
PORT = "8080"
USERS_JWT_PUBLIC_KEY = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxdk45a0ZxTnN1Um1uT0N4VmVpSwpWNGRYWDIxSjF1SXBuRmZNTFVubjNWQ0ttZFIrczZmV3hBVXozdGxWSGIwSHdVMFFsUGZPNTdtSEdaWkRiaGpxCnNzRGVENmRJb3p2TEQwMVJXaVova1RmRVV2YTdVaTdaVHlKYlJoY044L08xZ2s4TG8rVTF4N2NISEF4S2JlUnAKQUJPZmd2NHRqZ2JuTmhVaUhHa1YvZzNhbFN1VkdxRkRoUGZ5QTRMUTcrMHl5UktzME0yemxnYXNRbTdQRmt1NAo4d3VONTVDQ3RRVVc3dTVmSmYyNGtLQllYK0oyYW51SnRwS3NGMXluckh3a093TEZhSDgzNEU3cUYvNDJRcjlnCnluRTN2Vy9QOEZWZW5GOFkrSUpnTHZCc0tIcTdROHJRTU02b2lCNW5jYisyeG9XQ290VjlhSTNyQ0EveEt6ZzUKS1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="