name: CodeCov
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Generate report
        run: |
          source $(poetry env info --path)/bin/activate
          coverage run -m pytest
          coverage xml
      - name: Upload report to Codecov
        uses: codecov/codecov-action@v2
        with: 
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.xml
          fail_ci_if_error: false
          